### PR TITLE
Integrate a generator for Foundation 6

### PR DESCRIPTION
**Pull request by dustb0wl**
Create a generator template for foundation 6 and add to site.rb.

### CODE REVIEW

**Comment by did** [comment]
thanks @dustb0wl I don't know if we should keep the old version of foundation in Wagon. Any thoughts?

**Comment by nielsenramon** [comment]
@dustb0wl @did I would remove old versions to be honest :)

**Comment by did** [comment]
agreed @nielsenramon. @dustb0wl in your PR, could you please remove the old version of Foundation and also the README.md file. thanks!

**Comment by dustb0wl** [comment]
No problem - I had originally left it in because there are some significant changes from 5.x to 6.x, but I went ahead and removed 5 and renamed 6 to be just 'foundation' instead of 'foundation6' to reflect that it is now the only version of foundation in the package.

**Comment by did** [comment]
thanks @dustb0wl!!!

**Pull request merged**
