### PR TITLE
load bower_components

### PR DESCRIPTION
**Pull request by gregory**
This goes along with https://github.com/locomotivecms/mounter/pull/36

### CODE REVIEW

**Comment by jfturcot** [comment]
I like this, but I fixed it in my projects by putting the following in the .bowerrc
```json
{
  "directory": "public/javascripts/bower_components/",
}
```
I then make sure the bower components are required in my main asset file, a application.js and a application.css in my case.

It works for me without having to officially support bower in Wagon.

**Comment by gregory** [comment]
right, it'll work locally, i got that that point. 
But when you'll try to push to the engine, you'll have a bunch of errors since it'll push all the files in public/javascript/ :( 

That's part of the PR i made with mounter, just push the files that are in "main".

**Comment by jfturcot** [comment]
Oh I haven't seen the mounter PR, you are right, I had to white list all the extensions in Locomotive::ThemeAssetUploader of my Engine to make push work.

**Comment by gregory** [comment]
not only that, but also now you store a all bunch of crap on s3 just for it to work. like all the files that are not in the 'main' ...

**Comment by gregory** [comment]
ping @did :D

**Comment by planktin** [comment]
Hey guys,

I did something a bit different which you might find handy. It uses node/bower/grunt but encapsulated in its own wagon generator. I set up a few Grunt tasks to clean your public assets, copy *only* the useful files from bower_components (so Wagon doesn't have to upload 1000s of vendor files), and a watch task to auto compile SCSS on save. It's more explicit, but keeps your assets nice and clean. Works great for me.

You can get a Foundation 5 Libsass site up and running in a minute or 2.
https://github.com/planktin/wagon-generators

I kind of like the idea of having more specific use cases like this (with it's additional dependencies ala node/bower/grunt) in its own wagon generator, rather than being supported in the Locomotive CMS core.

**Pull request closed without merging**
