### PR TITLE
Let LiveReloadPlugin handle the script in the page's head

### PR DESCRIPTION
**Pull request by manuchap**
Use case: Pages not using the default layout.

### CODE REVIEW

**Comment by did** [comment]
good one @manuchap. Could you also please update the following file too?
https://github.com/locomotivecms/wagon/blob/master/generators/blank/app/assets/webpack.common.js
Thanks!

**Comment by manuchap** [comment]
Done :-)

**Comment by did** [comment]
@manuchap let me know when you'll be done ;-)

**Comment by manuchap** [comment]
😅 Tried to do separate pull requests for live reload and script loader(which was commented out as a bonus)  but I guess I can't.
I've kept the edit though in webpack.prod.js that was calling the wrong file.
Tell me if I should remove it to.

**Pull request closed without merging**
